[package]
name = "parallel"
version = "0.1.0"
authors = ["mito15 <mitosawada@gmail.com>"]

[dependencies]
ndarray = "0.11.0"
ndarray-rand = "0.7.0"
ndarray-parallel = "0.8"
rayon = "1.0"
rand = "0.4"
